# pod was deleted not needed BECAUSE I have a deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  labels:
    app: mongodb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-deployment
  template:
    metadata:
      name: mongodb-deployment
      labels:
        app: mongodb-deployment
    spec:
      containers:
        - name: mongodb-deployment
          image: mongo
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "gegabox"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "secret"
        
        - name: mongo-express
          image: mongo-express
          ports:
            - containerPort: 27017
          env:
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              value: "gegabox"
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              value: "secret"
            - name: ME_CONFIG_MONGODB_URL
              value: "mongodb://gegabox:secret@mongodb-service:27017"
            - name: ME_CONFIG_BASICAUTH_USERNAME
              value: "admin"
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
    
      