apiVersion: v1
kind: Service
metadata:
  name: hsqldb-service
spec:
  selector:
    app: hsqldb-deployment
  ports:
    - protocol: TCP
      port: 9001 # exposed by the service
      targetPort: 9001
      nodePort: 30009
  type: NodePort
  
  

  
  