# pod was deleted not needed BECAUSE I have a deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hsqldb-deployment
  labels:
    app: hsqldb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hsqldb-deployment
  template:
    metadata:
      name: hsqldb-deployment
      labels:
        app: hsqldb-deployment
    spec:
      containers:
        - name: hsqldb-deployment
          image: blacklabelops/hsqldb:latest
          ports:
            - containerPort: 9001
          env:
            - name: HSQLDB_DATABASE_NAME
              value: "trainingdb"
            - name: HSQLDB_DATABASE_ALIAS
              value: "trainingdb"
            - name: HSQLDB_USER
              value: "SA"
            - name: HSQLDB_PASSWORD
              value: ""
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
    
      